export * from './list-anime-by-featured'
export * from './get-top-ten-animes-by-likes'
export * from './list-anime-newest'
export * from './get-anime-by-id'
export * from './search-animes-by-name'
export * from './add-anime'
export * from './update-anime'
